Class {
	#name : #Gt4WExercise,
	#superclass : #Object,
	#instVars : [
		'sets',
		'rpes',
		'cycle',
		'index'
	],
	#category : #'Gt4Workouts-Model'
}

{ #category : #accessing }
Gt4WExercise >> children [
	^ {}
]

{ #category : #accessing }
Gt4WExercise >> cycle [
	^ cycle
]

{ #category : #accessing }
Gt4WExercise >> cycle: anObject [
	cycle := anObject
]

{ #category : #accessing }
Gt4WExercise >> index [
	^ index
]

{ #category : #accessing }
Gt4WExercise >> index: anObject [
	index := anObject
]

{ #category : #accessing }
Gt4WExercise >> rpes [
	^ rpes
]

{ #category : #accessing }
Gt4WExercise >> rpes: anObject [
	rpes := anObject
]

{ #category : #accessing }
Gt4WExercise >> sets [
	^ sets
]

{ #category : #accessing }
Gt4WExercise >> sets: anObject [
	sets := anObject
]
