Class {
	#name : #Gt4WExercise,
	#superclass : #Object,
	#instVars : [
		'sets',
		'rpes'
	],
	#category : #'Gt4Workouts-Model'
}

{ #category : #accessing }
Gt4WExercise >> children [
	^ {}
]

{ #category : #accessing }
Gt4WExercise >> rpes [
	^ rpes
]

{ #category : #accessing }
Gt4WExercise >> rpes: anObject [
	rpes := anObject
]

{ #category : #accessing }
Gt4WExercise >> sets [
	^ sets
]

{ #category : #accessing }
Gt4WExercise >> sets: anObject [
	sets := anObject
]
